# helm/tenora-chart/templates/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secrets.DATABASE_URL is required" .Values.secrets.secrets.DATABASE_URL | quote }}
  NEXTAUTH_SECRET: {{ required "secrets.NEXTAUTH_SECRET is required" .Values.secrets.NEXTAUTH_SECRET | quote }}
  NEXTAUTH_URL: {{ required "secrets.NEXTAUTH_URL is required" .Values.secrets.NEXTAUTH_URL | quote }}
  GOOGLE_CLIENT_ID: {{ required "secrets.GOOGLE_CLIENT_ID is required" .Values.secrets.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ required "secrets.GOOGLE_CLIENT_SECRET is required" .Values.secrets.GOOGLE_CLIENT_SECRET | quote }}
  GROQ_API_KEY: {{ required "secrets.GROQ_API_KEY is required" .Values.secrets.GROQ_API_KEY | quote }}