apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenora-app
  labels:
    app: tenora-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tenora-app
  template:
    metadata:
      labels:
        app: tenora-app
    spec:
      containers:
      - name: tenora-app
        image: niruth03/tenora:latest
        ports:
        - containerPort: 3000
