name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Push Docker Image
        run: |
          docker build -t niruth4405/tenora-ai:${{ github.sha }} .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u niruth4405 --password-stdin
          docker push niruth4405/tenora-ai:${{ github.sha }}

      - name: Update Image Tag in K8s Manifest
        run: |
          sed -i "s|image: niruth4405/tenora-ai:.*|image: niruth4405/tenora-ai:${{ github.sha }}|g" k8s/deployment.yaml
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add k8s/deployment.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}"
          git push